### ISSUE TITLE
license is missing

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/nexus#18]
all ocis code base shall be apache licensed - the license needs to be added to each and every repo

apache requires a certificate of origin - we shall enforce this when pushing to the repos

**Comment by butonic** [comment]
@DeepDiver1975 um https://github.com/owncloud/nexus/blob/master/LICENSE Apache2 for nexus. all other repos have their own license: 
- https://github.com/owncloud/phoenix/blob/master/LICENSE AGPL3
- https://github.com/cernbox/reva/blob/master/LICENSE currently AGPL3

**Comment by butonic** [comment]
reva is now officially Apache 2 Licensed. Closing

**Comment by DeepDiver1975** [comment]
> apache requires a certificate of origin - we shall enforce this when pushing to the repos

what about this?

**Comment by butonic** [comment]
@labkode can you setup https://github.com/probot/dco for https://github.com/cs3org/reva?

**Comment by labkode** [comment]
@butonic @DeepDiver1975 we avoid DCO because the copyright states the following:

https://github.com/cs3org/.github/blob/master/COPYRIGHT.md#explicit-agreement
