### ISSUE TITLE
reva: add ldap mapping config options

### ISSUE THREAD

**Issue by butonic** [owncloud/nexus#19]
- [x] username attribute (default to `samAccountName` ... see discussion about objectsid vs objectguid etc)
- [x] mail attribute, default to `mail`
- [x] display name attribute (default to `displayName`)
- [x] group membership attribute (default to `memberOf` but allow emptystring to skip group mapping)

do not add guessing magic. if something changes another tool needs to update existing data if that is possible at all.

see Lines https://github.com/owncloud/reva/blob/f4f9610aee232d95b874f51144f57bee66947396/pkg/user/manager/ldap/ldap.go#L84
and https://github.com/owncloud/reva/blob/f4f9610aee232d95b874f51144f57bee66947396/pkg/user/manager/ldap/ldap.go#L102-L107

**Comment by refs** [comment]
🚢  https://github.com/cs3org/reva/pull/216
