### ISSUE TITLE
oidc authentication

### ISSUE THREAD

**Issue by butonic** [owncloud/nexus#2]
The new reva does notd yet contain a working oidc auth_manager. http://github.com/cernbox/reva/cmd/revad/svcs/httpsvcs/handlers/auth/credential/strategy/oidc/oidc.go is a leftover from an experiment with the old reva.

Setting `credential_strategy = "oidc"` in revad.toml gives a segfault

**Comment by butonic** [comment]
@labcoke waiting on https://github.com/owncloud/phoenix/issues/573

**Comment by butonic** [comment]
added a hardcoded version that works with kopano in https://github.com/owncloud/reva/blob/master/cmd/revad/svcs/httpsvcs/handlers/auth/credential/strategy/oidc/oidc.go

**Comment by butonic** [comment]
the oidc auth currently only works with a kopano konnect IdP because it will read the username from a special sub claim: https://github.com/cernbox/reva/pull/37/commits/e658e03fdaec5ec61971dcb811da569678cfe391#diff-212e0ef911e5b733efc4ee555ac08126R77

we need to decide how we want to handle users. storages need to track users by an ID that does not change, even when the user is renamed. keep in mind that a storage provider for wnd should use the current samaccountname or DOMAIN/samaccountname or the upn to mount the storage. that will give the user the right permissions. If storage is local we need to look up the objectsid and create a storage for that. whenever a user is authenticated we need to check his sid and the sid history to get the correct storage ... which is meh ... but guid might change when a user is copied. sidhistory actually keeps track of all sids ... well, or we keep that out of the auth and let the storage do the sid lookup based on the username ... hm

**Comment by butonic** [comment]
I like the idea of passing subject and issuer as properties of the user along to the storage providers. It would make storing a unique id unnecessary. but how do we make shares correctly identify users?
the storage implementations could use subject and issuer to create the share. but it would require being able to look up subject and issuer at the idp, which brings us back to [SCIM](http://www.simplecloud.info/) ... I need to think on this. Your thoughts are welcome.

**Comment by butonic** [comment]
Fleshed out my thoughts in https://github.com/Kopano-dev/konnect/issues/3. a scim backend would move the problem to a separate service and provide us with a list of stable non-reassignable userids.

**Comment by butonic** [comment]
hm maybe
- `uniqueIdentifier` [rfc4524#section-2.24](https://tools.ietf.org/html/rfc4524#section-2.24) from the [cosine.schema](https://github.com/openshift/openldap/blob/master/2.4.41/contrib/config/schema/cosine.schema#L688)
- `serialNumber` [rfc2256#section-5.6](https://tools.ietf.org/html/rfc2256#section-5.6) from the [core.schema](https://github.com/openshift/openldap/blob/master/2.4.41/contrib/config/schema/core.schema#L89-L93)
- `x500UniqueIdentifier` [rfc2256#section-5.46](https://tools.ietf.org/html/rfc2256#section-5.46) from the [core.schema](https://github.com/openshift/openldap/blob/master/2.4.41/contrib/config/schema/core.schema#L301-L304) but it is a bitstring
- `employeeNumber` [rfc2798#section-2.4](https://tools.ietf.org/html/rfc2798#section-2.4) from the [inetOrgPerson.schema](https://github.com/openshift/openldap/blob/master/2.4.41/contrib/config/schema/inetorgperson.schema#L64-L70) ... well ... subject to change I fear, not technical enough
- write our own SCIM schema that we use in a dedicated SCIM service to manipulate an openldap server (ad natively speaks scim, if not [AD also supports adding attributes](https://social.technet.microsoft.com/wiki/contents/articles/51121.active-directory-how-to-add-custom-attribute-to-schema.aspx) )

In any case, I recommend using scim as we need an api to look up users AND the subject anyway.

**Comment by butonic** [comment]
Here is a different approach that we could take if the oidc token contains a username (eg `preferred_username` or for kopane `kc\.identity.kc\.i\.un`).

## Preface
While a username is neither globally unique nor non-reassignable, it uniquely identifies a user in a system at a given point in time. So we can use it to identify a user during authentication (which is why logins with username and password work). The email is a better login identifier, because it is scoped: it also contains a domain. That allows a system to differentiate two users `bob@company.com` and `bob@foobarable.com` which might otherwise have the same usernname `bob`. This is why Active Directory has the userPrincipalName, which is the scoped `samaccountname@domain`.

## Passing the username
since a request is short lived we can pass the username (or better a user object with unername, email and displayname) along. Every service can then use that user object.

### Storage Providers
The storage providers could either
1. use the username directly to access the filesystem
2. lookup a uuid for the username (or use the sub) to chose the correct storage

The first way would work for eos and also for WND, because WND ultimately needs to authenticate the request against an SMB service, which takes a username and a password (which we still need to store, or we use kerberos). 

The second way (with uuid lookup) is actually more complicated, but technically, this is what eg smb or eos do internally, they find the sid / uid respectively and will only grant access based on that. The username is irrelevant after auth. Just look at your posix filesystem: the owner and group are numeric.

### sharing
To share, the user needs to look up a user in a dictionary (ldap, scim, whatever). With the username  from the result it can tell the storage hey share this file with this user. Now, there are several lookups that need to be possible:
1. The storage again need to lookup a uuid for the username. Unfortunately, the subject for users is not exposed by most IdPs ... by design. Some IdPs have a SCIM api which we could use to get a uuid. 
2. when looking at a file on the storage it must be possible to lookup the user (including displayname, email etc) based on the uuid so we can show who has access to a file.

### federated sharing
definitely needs a uuid for a user, otherwise shares will break when a username changes.
can be implemented with a federated storage that internally looks up a uuid for a user and exposes that for sharing.

### other services
if comments or tags are stored on disk the user that originally did that needs to be stored with a stable attribute. This calls for a uuid lookup again.

## benefits
- when pushing uuid lookup to the storage we can keep the auth code simpler.
- no weird try to identfy a user based on the username ... well actually a posix storage would have that problem.

## downsides
every service might have to implement a uuid lookup ... which would lead to another service (SCIM). Back to square one

## conclusion
We should implement a scim service that is responsible for generating a uuid for every user. we need it for federated sharing and some storages may need it to prevent data and exposure loss when usernames change or are reused.

That service is queried after auth the always lookup a uuid that is passed along. It can be used by subsequent services but is optional. It could be a reva uuid_manager, similar to auth_manager and user_manager.

## Links
Also see [the shibboleth wiki for a discussion on name identifier properties](https://wiki.shibboleth.net/confluence/display/CONCEPT/NameIdentifiers).

**Comment by longsleep** [comment]
> Here is a different approach that we could take if the oidc token contains a username (eg `preferred_username` or for kopane `kc\.identity.kc\.i\.un`).

There are some thoughts about this in https://openid.net/specs/openid-connect-core-1_0.html#ClaimStability

I will also add support for the `preferred_username` claim to the Kopano Konnect kc and ldap backends as part of the profile scope.

**Comment by butonic** [comment]
oidc works
- [ ] config tracked in https://github.com/owncloud/nexus/issues/31 
- [ ] changes need to be pushed upstream ...
