### ISSUE TITLE
Add what is reva in README.md

### ISSUE THREAD

**Issue by mmattel** [owncloud/nexus#23]
Suggestion to add the following in README.md:

...
This repository is used a a starting point for collaboration on integrating reva with phoenix an IdP and other components. `For more information about reva visit: https://github.com/cernbox/reva`
...

This makes it easier to know what reva is about, else it is hard to find.

I can't do a PR as I do not have write access to this repro.

@butonic FYI

**Comment by butonic** [comment]
@mmattel Thx, I updated the Readme and makefile.
