### ISSUE TITLE
Remove Private Keys

### ISSUE THREAD

**Issue by mr-r0w07** [owncloud/nexus#44]
Hi,

I was participating in owncloud bug bounty program on hackerone and found out that you are leaking private keys at https://github.com/owncloud/nexus/blob/master/configs/ssl/private-key.pem. Even if they are test keys, this is not a good security practice.

Further, you are also leaking JWT secret key at all the files under https://github.com/owncloud/nexus/tree/master/configs/reva  folder.

Please, remove the keys and rotate them!

Regards
Vikas Rawat
https://hackerone.com/mr_r0w07

**Comment by tboerger** [comment]
It's not planned to remove the files, they are used for development and local testing.

**Comment by mr-r0w07** [comment]
hi @tboerger 

I was asked to open an issue here by owncloud's security team on hackerone.
Just wanted to confirm this only if they are for testing or deployed officially.
Closing this issue now!

Thanks,
