### ISSUE TITLE
make down not possible when phoenix src is missing

### ISSUE THREAD

**Issue by butonic** [owncloud/nexus#48]
when I run make down, I'm getting the below error
ERROR: build path /Users/hana/nexus/build/phoenix/src either does not exist, is not accessible, or is not a valid URL.
make: *** [down] Error 1

**Comment by butonic** [comment]
I will double check this. As a work around just create the directory:
```
mkdir -p  /Users/hana/nexus/build/phoenix/src
```
Let me know if that helps.

cc @HanaGemela

**Comment by HanaGemela** [comment]
Yes, it helped. I'm not getting the error anymore

**Comment by butonic** [comment]
closing because we are moving issues to the ocis repo
