### ISSUE TITLE
CD pipeline ready deployment

### ISSUE THREAD

**Issue by butonic** [owncloud/nexus#51]
We want to be able to test the current code base:
- [ ] with a CD process that builds and deploys nexus:
  - reverse proxy
  - oidc provider
  - phoenix
  - revad
  - eos
- [ ] with a local deployment to test migrations from oc10 to ocis

see https://github.com/owncloud/ocis

**Comment by tboerger** [comment]
I don't really understand what you want to build and deploy, and where.

**Comment by butonic** [comment]
I guess a phoenix.owncloud.com like deployment, but with ocis on top of eos ... or posix / owncloud storage

**Comment by butonic** [comment]
implemented for ocis!
